# Generated by Django 3.1.6 on 2021-04-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20210324_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birth',
        ),
    ]
