# Generated by Django 3.1.6 on 2021-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210418_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password2',
            field=models.CharField(default='000000', max_length=20, verbose_name='Password2'),
        ),
    ]
