# Generated by Django 3.1.6 on 2021-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20210418_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='passwor1',
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default='111111', max_length=8, verbose_name='Password2'),
        ),
    ]
