# Generated by Django 3.1.6 on 2021-05-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20210418_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='Tid',
            new_name='tid',
        ),
    ]
