# Generated by Django 3.1.6 on 2021-05-06 11:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20210504_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
