# Generated by Django 3.1.6 on 2021-05-06 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_auto_20210506_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
