# Generated by Django 3.1.6 on 2021-03-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('subject', models.CharField(default='', max_length=20, verbose_name='Subject')),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=1, verbose_name='score')),
            ],
            options={
                'verbose_name': 'Single choice question bank',
                'verbose_name_plural': 'Single choice question bank',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='student number')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Shemale', 'Shemale')], default='Male', max_length=10, verbose_name='Gender')),
                ('dept', models.CharField(choices=[('Comp', 'Computer Science'), ('BioChem', 'BioChemistry'), ('Bio', 'BioChemistry')], default=None, max_length=100, verbose_name='Department')),
                ('major', models.CharField(default=None, max_length=20, verbose_name='professional')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Mailbox')),
                ('password', models.CharField(default='111', max_length=20, verbose_name='Password')),
                ('birth', models.DateField(verbose_name='Date Of Birth')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Teacher ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('username', models.CharField(default=None, max_length=20, verbose_name='Username')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Shemale', 'Shemale')], default='Male', max_length=10, verbose_name='Gender')),
                ('dept', models.CharField(choices=[('Comp', 'Computer Science'), ('BioChem', 'BioChemistry'), ('Bio', 'BioChemistry')], default=None, max_length=20, verbose_name='College')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='mailbox')),
                ('password', models.CharField(default='000000', max_length=20, verbose_name='password')),
                ('birth', models.DateField(verbose_name='date of birth')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=20, verbose_name='Course')),
                ('instruction', models.TextField()),
                ('major', models.CharField(max_length=20, verbose_name='Applicable for test papers')),
                ('exam_time', models.DateTimeField()),
                ('Tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.teacher')),
                ('pid', models.ManyToManyField(to='exam.Exam')),
            ],
            options={
                'verbose_name': 'Test paper',
                'verbose_name_plural': 'Test paper',
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=20, verbose_name='Subject')),
                ('grade', models.IntegerField()),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievement',
                'db_table': 'grade',
            },
        ),
    ]
