# Generated by Django 3.1.6 on 2021-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='Username'),
        ),
    ]
