# Generated by Django 3.1.6 on 2021-03-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210322_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Examination Question Bank', 'verbose_name_plural': 'Examination Question Bank'},
        ),
    ]
