# Generated by Django 3.1.6 on 2021-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210323_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('Maths_&_Comp', 'Maths and Computer Science'), ('BioChem', 'BioChemistry'), ('Accounting', 'Accounting'), ('Economics', 'Economics'), ('History', 'History'), ('Mass Commuication', 'Mass Commuication')], default='', max_length=100, verbose_name='Department'),
        ),
    ]
