# Generated by Django 3.1.6 on 2021-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210413_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='000000', max_length=20, verbose_name='Password'),
        ),
    ]
