# Generated by Django 3.1.6 on 2021-04-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210413_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
