# Generated by Django 3.1.6 on 2021-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=8, verbose_name='Password'),
        ),
    ]
