# Generated by Django 3.1.6 on 2021-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210415_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='111111', max_length=8, verbose_name='Password'),
        ),
    ]
