# Generated by Django 3.1.6 on 2021-04-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20210418_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passwor1',
            field=models.CharField(default='111111', max_length=10, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password2',
            field=models.CharField(default='111111', max_length=10, verbose_name='Password2'),
        ),
    ]
